### PR TITLE
strnset() strset() strlwr() strupr() strrev() swab() bzero() strlcat() strlcmp() timingsafe_Xcmp()

### PR DESCRIPTION
**Pull request by spacerace**
Another few patches :)

### CODE REVIEW

**Comment by spacerace** [comment]
**OpenBSD's timingsafe_bcmp() and timingsafe_memcmp():**
these functions are made for security purposes. everytime one of
these is called it will take same amount of time. see documentation
from OpenBSD for more information (man 3 timinsafe*).

There is another possible use, why I put it in here. In MS-DOS
targets with an timer IRQ you could get hard real time behaviour.
With these functions for comparing data in IRQ routine you will
be able to precisely calculate timing diagrams.
useful for schedulers, motor control, video output?, ...

**strlcat() and strlcpy()**
These functions take care of string termination, also BSD origin.

** rest **
already was in last pull request. Sadly I don't know how to split. Github makes all into one pull request now. I rather wanted to have it 2 different pull requests, but not every wish is granted ;)

**Comment by mfld-fr** [comment]
No problem. Just a question please : what is your goal in improving `dev86` ? AFAIK, this @jbruchon 's fork was intended to maintain `dev86` as long as it was used by ELKS. But now we are migrating from `dev86` to @tkchia 's `gcc-ia16`. So it would be interesting to know what is your use case ? Thanks anyway for your latest contributions.

**Comment by spacerace** [comment]
In short, DOS is my target.
Longer: I wanted to use dev86 on my linux box, rather than Borland CPP on my old DOS-laptop. The system()/exec*-stuff was totally missing, also these few string functions 
(like strnset for ASCII user interface drawing, other not needed now, but useful like strupr/lwr...)

strl* for having safer, not totally safe, string functions. timingsafe functions I use for doing digital IO with stepper motor controllers in an embedded system.
...

Also conio is missing a lot of stuff. (no colors, no highlighting, ...), this is where I am just right now working on.

**Comment by tkchia** [comment]
Hello @spacerace,

Well, I personally would prefer to use either `gcc-ia16` and/or the Open Watcom compiler (which is under a rather free license too) when targeting DOS from Linux.  I feel that the `dev86` compiler and runtime is very limited in several ways --- though I suppose you might have your own reasons for wanting to use it.

Thank you!

**Comment by tkchia** [comment]
Hello @spacerace,

Also, if you wish to create two separate pull requests at the same time in GitHub, the way to do this is to create two branches in your Git repository, and submit a pull request for each branch.

Thank you!

**Comment by tkchia** [comment]
Hello @spacerace,

Whatever goes for you, I suppose. :-)

Hello @mfld-fr ,

On second thought, I think @spacerace's patches might come in useful even if ELKS switches to `gcc-ia16` --- since I recall that the general plan is to use `gcc-ia16` together with `dev86`'s `elks-libc` rather than Newlib.

(My main wonder is how (or if) we can include GCC's multilib support into the `elks-libc` build process.  But that is probably a whole other topic.)

Thank you!

**Comment by mfld-fr** [comment]
@tkchia : this is totally out of this PR context, but I have to respond to your question : actually ELKS forked the `dev86` `libc` and now maintains its own ELKS `libc`, so there is no more link between this project and ELKS. Currently `gcc-ia16` is used as a naked compiler, and might later be linked to ELKS `libc`.

**Comment by jbruchon** [comment]
I'm going to merge this unless someone has a problem with it. Let me know.

**Pull request merged**
